; ----------------------------------------------------------------------------
; FILE: Format.Inc
; DATE: December 18, 2001
; DESCRIPTION: Include it to use formatting routines.
; ----------------------------------------------------------------------------
Extrn _bin2reg32 : Near
Extrn _bin2reg16 : Near
Extrn _bin2reg8 : Near
Extrn _reg32tobin : Near
Extrn _reg16tobin : Near
Extrn _reg8tobin : Near
Extrn _atoi : Near
Extrn _atou : Near
Extrn _hex2u32 : Near
Extrn _hex2u16 : Near
Extrn _hex2u8 : Near
Extrn _u32_2hex : Near
Extrn _u16_2hex : Near
Extrn _u8_2hex : Near
Extrn _utoa : Near
Extrn _itoa : Near
